cmake_minimum_required(VERSION 3.2)
file(STRINGS ${INPUT_FILENAME} LINES)
file(STRINGS ${PATTERNS_FILENAME} PATTERNS)
file(WRITE ${OUTPUT_FILENAME} "")
foreach(PATTERN IN LISTS PATTERNS)
	if(PATTERN MATCHES "grep '(.*)' tmp.h | sed -e 's|^.*\\\(stringpool_str[0-9]*\\\).*$|  \(int\)\(long\)\\&\(\(struct stringpool_t *\)0\)->\\1,|'")
		set(PATTERN ${CMAKE_MATCH_1})
		string(REPLACE "(" "\\(" PATTERN ${PATTERN})
		string(REPLACE ")" "\\)" PATTERN ${PATTERN})
		foreach(LINE IN LISTS LINES)
			if(LINE MATCHES "^.*\(stringpool_str[0-9]*\)\\[${PATTERN}\\].*$")
				file(APPEND ${OUTPUT_FILENAME} "  (int)(long)&((struct stringpool_t *)0)->${CMAKE_MATCH_1},\n")
			endif()
		endforeach()
	endif()
endforeach()
